// Generated by CoffeeScript 1.6.3
(function() {
  var Lab, after, authentication, before, configs, describe, expect, it, routes, server;

  Lab = require('lab');

  configs = require('../../lib/config/index');

  server = require('../../lib/server');

  authentication = require('../../lib/authentication');

  routes = require('../../lib/routes');

  expect = Lab.expect;

  before = Lab.before;

  after = Lab.after;

  describe = Lab.experiment;

  it = Lab.test;

  describe("/users/", function() {
    return it("returns an error when requested without auth", function(done) {
      var authModuleError, hapiServer;
      hapiServer = server(configs.server);
      hapiServer = hapiServer.server;
      authModuleError = authentication(hapiServer, configs.authentication);
      expect(authModuleError).to.equal(void 0);
      hapiServer.addRoutes(routes);
      return hapiServer.inject("/users/", function(res) {
        expect(res.statusCode).to.equal(401);
        expect(res.result.err).to.equal('unauthenticated');
        return done();
      });
    });
  });

  describe("/questions/", function() {
    return it("returns questions object", function(done) {
      var authModuleError, hapiServer;
      hapiServer = server(configs.server);
      hapiServer = hapiServer.server;
      authModuleError = authentication(hapiServer, configs.authentication);
      hapiServer.addRoutes(routes);
      return hapiServer.inject("/questions/", function(res) {
        expect(res.statusCode).to.equal(200);
        expect(res.result.questions[0].Q).to.equal('Did you eat food?');
        expect(res.result.questions[1].Q).to.equal('Was it mostly plants?');
        return done();
      });
    });
  });

}).call(this);
