// Generated by CoffeeScript 1.6.3
(function() {
  var Lab, after, authentication, before, configs, describe, expect, it, routes, server;

  Lab = require('lab');

  configs = require('../../lib/config/index');

  server = require('../../lib/server');

  authentication = require('../../lib/authentication');

  routes = require('../../lib/routes');

  expect = Lab.expect;

  before = Lab.before;

  after = Lab.after;

  describe = Lab.experiment;

  it = Lab.test;

  describe("Boom", function() {
    return it("returns an login redirect when constructed without auth", function(done) {
      var hapiServer;
      hapiServer = server(configs.server);
      hapiServer = hapiServer.server;
      hapiServer.addRoutes(routes);
      return hapiServer.inject("/home", function(res) {
        expect(res.statusCode).to.equal(302);
        expect(res.headers.location).to.equal('http://127.0.0.1:3333/login');
        return done();
      });
    });
  });

  describe("Boom", function() {
    return it("returns an error with info when constructed using another error", function(done) {
      var authModuleError, hapiServer;
      hapiServer = server(configs.server);
      hapiServer = hapiServer.server;
      authModuleError = authentication(hapiServer, configs.authentication);
      expect(authModuleError).to.equal(void 0);
      hapiServer.addRoutes(routes);
      return hapiServer.inject("/home", function(res) {
        console.log('res: ', res);
        expect(res.statusCode).to.equal(302);
        expect(res.headers.location).to.equal('http://127.0.0.1:3333/login');
        return done();
      });
    });
  });

}).call(this);
