// Generated by CoffeeScript 1.6.3
(function() {
  var Hapi, Lab, Shot, after, authentication, before, configs, describe, expect, it, routes, server, utils;

  Lab = require('lab');

  Shot = require('shot');

  Hapi = require('hapi');

  configs = require('../../lib/config/index');

  server = require('../../lib/server');

  utils = require('../../lib/utilities');

  authentication = require('../../lib/authentication');

  routes = require('../../lib/routes');

  expect = Lab.expect;

  before = Lab.before;

  after = Lab.after;

  describe = Lab.experiment;

  it = Lab.test;

  describe('Utils isDevelopment', function() {
    return it('should return false', function(done) {
      expect(utils.isDevelopment()).to.be["false"];
      return done();
    });
  });

  describe('Utils getMarkDownHTML', function() {
    var html;
    html = void 0;
    before(function(done) {
      return utils.getMarkDownHTML('API.md', function(err, data) {
        expect(err).to.not.exist;
        html = data;
        return done();
      });
    });
    return it('should convert API.md to HTML', function(done) {
      expect(html).to.have.string('<h1 id="mirrormonkey-api">');
      return done();
    });
  });

}).call(this);
