// Generated by CoffeeScript 1.6.3
(function() {
  var Hapi, exports;

  use(strict);

  /*
  * ---
  *   Authentication module
  *   @name suthentication
  *   @api public
  */


  Hapi = require('hapi');

  exports = module.exports = function(hapiServer, config) {
    var retVal, _ref, _ref1;
    retVal = void 0;
    if ((typeof configs !== "undefined" && configs !== null ? configs.authentication : void 0) && (hapiServer != null ? (_ref = hapiServer.plugins) != null ? (_ref1 = _ref.travelogue) != null ? _ref1.passport : void 0 : void 0 : void 0)) {
      configs.authentication.passport = hapiServer.plugins.travelogue.passport;
      hapiServer.pack.allow({
        ext: true
      }).require('mf-auth-api', configs, function(err) {
        console.log("cb");
        if (err) {
          return retVal = '[ error ] Index: plugin mf-auth-api load error: ' + err;
        } else {
          return console.log('[ start ] mf-auth-api plugin loaded');
        }
      });
    } else {
      retVal = "Server module: Invalid configuration object";
    }
    console.log("returning");
    return retVal;
  };

}).call(this);
