// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Authentication module
  *   @name authentication
  *   @api public
  */

  var Hapi, exports;

  Hapi = require('hapi');

  exports = module.exports = function(hapiServer, config) {
    var _ref, _ref1;
    Hapi.utils.assert((hapiServer != null ? (_ref = hapiServer.plugins) != null ? (_ref1 = _ref['travelogue-fork']) != null ? _ref1.passport : void 0 : void 0 : void 0) != null, 'Athentication module: Passport plugin not found');
    Hapi.utils.assert(config != null, "Athentication module: Invalid configuration object " + config);
    config.passport = hapiServer.plugins['travelogue-fork'].passport;
    return hapiServer.pack.allow({
      ext: true
    }).require('mf-auth-api', config, function(err) {
      Hapi.utils.assert(!err, "Athentication module: " + err);
      return hapiServer.log(['init'], 'Athentication module: mf-auth-api plugin loaded');
    });
  };

}).call(this);
