// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Authentication module
  *   @name authentication
  *   @api public
  */

  var Hapi, exports;

  Hapi = require('hapi');

  exports = module.exports = function(hapiServer, config) {
    var retVal, _ref, _ref1;
    retVal = void 0;
    if (config && (hapiServer != null ? (_ref = hapiServer.plugins) != null ? (_ref1 = _ref.travelogue) != null ? _ref1.passport : void 0 : void 0 : void 0)) {
      config.passport = hapiServer.plugins.travelogue.passport;
      hapiServer.pack.allow({
        ext: true
      }).require('mf-auth-api', config, function(err) {
        if (err) {
          return retVal = '[ error ] Athentication: plugin mf-auth-api load error: ' + err;
        } else {
          return console.log('[ start ] mf-auth-api plugin loaded');
        }
      });
    } else {
      retVal = '[ error ]  Athentication: Invalid configuration object';
    }
    return retVal;
  };

}).call(this);
