// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Server Index
  *   @name index
  *   @api public
  */

  var authentication, configs, hapiServer, routes, server, swagger, swaggerError, utils;

  utils = require('./utilities');

  configs = require('./config');

  server = require('./server');

  authentication = require('./authentication');

  routes = require('./routes');

  swagger = require('./swagger');

  hapiServer = server(configs.server);

  if (configs.authentication) {
    authentication(hapiServer, configs.authentication);
  }

  if (utils.isDevelopment()) {
    hapiServer.on('log', function(event, tags) {
      if (tags.error) {
        return console.error(event);
      } else {
        return console.log(event);
      }
    });
  }

  hapiServer.addRoutes(routes);

  hapiServer.start(function() {
    return hapiServer.log(['init'], "server started " + hapiServer.info.uri);
  });

  swaggerError = swagger(hapiServer, configs.server);

  if (swaggerError) {
    throw swaggerError;
  }

}).call(this);
