// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Server Index
  *   @name index
  *   @api public
  */

  var authModuleError, authentication, configs, hapiServer, routes, server, swagger, swaggerError, utils;

  utils = require('./utilities');

  configs = require('./config');

  server = require('./server');

  authentication = require('./authentication');

  routes = require('./routes');

  swagger = require('./swagger');

  hapiServer = server(configs.server);

  if (!hapiServer.server || hapiServer.error) {
    throw hapiServer.error || '[ error ] index: Unexpected error!';
  }

  hapiServer = hapiServer.server;

  if (configs.authentication) {
    authModuleError = authentication(hapiServer, configs.authentication);
    if (authModuleError) {
      throw authModuleError;
    }
  }

  if (utils.isDevelopment) {
    hapiServer.on('internalError', function(event) {
      console.error('[ error ] index: Internal error!');
      return console.error(event);
    });
  }

  hapiServer.addRoutes(routes);

  hapiServer.start(function() {
    return console.log('server started ', hapiServer.info.uri);
  });

  swaggerError = swagger(hapiServer, configs.server);

  if (swaggerError) {
    throw swaggerError;
  }

}).call(this);
