// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Routes module
  *   @name routes
  *   @api public
  */

  var Types, apiHandler, pack, utils;

  pack = require('../package');

  utils = require('./utilities');

  Types = require('hapi').types;

  apiHandler = function(request) {
    return utils.getMarkDownHTML(__dirname + '/../API.md', function(err, data) {
      return request.reply.view('swagger.html', {
        title: pack.name,
        markdown: data
      });
    });
  };

  module.exports = [
    {
      method: 'GET',
      path: '/home',
      config: {
        auth: 'passport',
        handler: function(request) {
          return request.reply('ACCESS GRANTED<br/><br/>');
        }
      }
    }, {
      method: 'GET',
      path: '/',
      config: {
        handler: apiHandler
      }
    }, {
      method: 'GET',
      path: '/api/{path*}',
      handler: {
        directory: {
          path: './public',
          listing: false,
          index: true
        }
      }
    }
  ];

}).call(this);
