// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Server module
  *   @name server
  *   @api public
  */

  var Hapi, exports;

  Hapi = require('hapi');

  exports = module.exports = function(config) {
    var pluginConfigs, serverInst, validConf;
    validConf = ((config != null ? config.host : void 0) != null) && (config.port != null) && (config.options != null) && (config.plugins != null);
    Hapi.utils.assert(validConf, "Server module: Invalid configuration object: " + config);
    serverInst = new Hapi.Server(config.host, config.port, config.options);
    pluginConfigs = config.plugins;
    if (pluginConfigs['travelogue-fork']) {
      pluginConfigs['travelogue-fork'] = config;
    }
    serverInst.pack.allow({
      ext: true
    }).require(pluginConfigs, function(err) {
      return Hapi.utils.assert(!err, "Server module: " + err);
    });
    return serverInst;
  };

}).call(this);
