// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Swagger module
  *   @name swagger
  *   @api public
  */

  var Hapi, exports, pack;

  Hapi = require('hapi');

  pack = require('../package');

  exports = module.exports = function(hapiServer, config) {
    var retVal, swaggerOptions;
    retVal = void 0;
    Hapi.utils.assert(hapiServer, 'Swagger module: invalid server');
    Hapi.utils.assert(config, 'Swagger module: Invalid configuration object');
    swaggerOptions = {
      basePath: config.url,
      constth: config.url,
      apiVersion: pack.version
    };
    return hapiServer.pack.allow({
      ext: true
    }).require('hapi-swagger', swaggerOptions, function(err) {
      Hapi.utils.assert(!err, "Swagger module: " + err);
      return hapiServer.log(['init'], 'Swagger module: hapi-swagger plugin loaded');
    });
  };

}).call(this);
