// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *   Swagger module
  *   @name swagger
  *   @api public
  */

  var exports, pack;

  pack = require('../package');

  exports = module.exports = function(hapiServer, config) {
    var retVal, swaggerOptions;
    retVal = void 0;
    if (config && hapiServer) {
      swaggerOptions = {
        basePath: config.url,
        constth: config.url,
        apiVersion: pack.version
      };
      hapiServer.pack.allow({
        ext: true
      }).require('hapi-swagger', swaggerOptions, function(err) {
        if (err) {
          return retVal = '[ error ] Swagger: plugin swagger load error: ' + err;
        } else {
          return console.log('[ start ] swagger plugin loaded');
        }
      });
    } else {
      retVal = '[ error ] Swagger : Invalid configuration object';
    }
    return retVal;
  };

}).call(this);
