// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *
  * @name config/constants
  * @api public
  */

  /*
  *  Environment types
  * @enum {string}
  * @type {string}
  */

  var environmentType;

  environmentType = {
    DEVELOPMET: 'development',
    PRODUCTION: 'production',
    TEST: 'test'
  };

  module.exports = {
    envType: environmentType
  };

}).call(this);
