// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *
  * @name config/index
  * @api public
  */

  var authConf, envType, serverConf;

  serverConf = require('./server');

  authConf = require('./authentication');

  envType = require('./constants').envType;

  module.exports = {
    envType: envType,
    server: serverConf,
    authentication: authConf
  };

}).call(this);
