// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  /*
  * ---
  *
  * @name config/index
  * @api public
  */

  var authConf, env, serverConf;

  env = require('../utilities').env;

  serverConf = require('./server');

  authConf = require('./authentication');

  module.exports = {
    server: serverConf[env],
    authentication: authConf[env]
  };

}).call(this);
